# Generated by Django 4.2.17 on 2025-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
